 
=============================================================
The time and date is 03/09/2016 15:29:22
Execution ID: 1457530162127_803100F
Execution folder is /home/tamirk/dt_executions/1457530162127_803100
Log file is in /home/tamirk/cloudify-cosmo/cloudify-deployment-tool/dev/output_1457530162127_803100.log
=============================================================
set_virtualenv: execution id : 1457530162127_803100
Activating virtualenv 'cfy_3_3_1ga_env'
=============================================================
install_cfy: execution id : 1457530162127_803100
/home/tamirk/cfy_versions_root /home/tamirk/cloudify-cosmo/cloudify-deployment-tool
----------------------------------------------------------
Running installCfy.sh ... 
  Required CFY VERSION      : 3.3.1GA
  CFY_MINOR_VERSION is      : 3.3.1
  PLUGINS_MINOR_VERSION is  : 1.3.1
  CFY_GIT_TAG_BRANCH is     : ga
  PLUGINS_GIT_TAG_BRANCH is : ga
Cloudify 3.3.1 ga version already exists (/home/tamirk/cfy_versions_root/3.3.1/ga). -Moving on.
/home/tamirk/cloudify-cosmo/cloudify-deployment-tool
=============================================================
install_cfy_cloud_provider_plugin: execution id : 1457530162127_803100
Cloud Provider                           : datacentred
Cloud user name                          : undefined
Application name                         : bs
Upload Blueprints ?                      : true
Blueprint suffix                         : _ttt0903
Blueprint file name                      : bosskin_blueprint.yaml
Deploy_Application ?                     : true
CFY_DATA_CENTRED_REGION                  : sal01 ...
CFY_DATA_CENTRED_OS                      : 74ff4015-aee1-4e02-aaa8-1c77b2650394 ...
CFY_DATA_CENTRED_MANAGER_SSH_USER        : undefined ...
CFY_DATA_CENTRED_DATACENTRED_FLAVOR      : undefined ...
CFY_DATA_CENTRED_AGENT_SSH_USER          : undefined ...
CFY_DATA_CENTRED_SERVER_NAME             : server-0203 ...
CFY_DATA_CENTRED_EXTERNAL_NETWORK_NAME   : undefined ...
CFY_DATA_CENTRED_MANAGEMENT_NETWORK_NAME : mngmnt-net-0203 ...
CFY_DATA_CENTRED_MANAGEMENT_SUBNET_NAME  : mngmnt-subnet-0203 ...
CFY_DATA_CENTRED_MANAGEMENT_ROUTER       : mngmnt-router-0203 ...
CFY_DATA_CENTRED_MANAGER_PORT_NAME       : mngr-port-0203 ...
CFY_DATA_CENTRED_MANAGER_SECURITY_GROUP  : mngr-sec-grp-0203 ...
CFY_DATA_CENTRED_AGENT_SECURITY_GROUP    : agent-sec-grp-0203 ...
CFY_DATA_CENTRED_SSH_KEY_FILE_NAME       : ~/.ssh/cloudify-manager-kp-0203.pem ...
CFY_DATA_CENTRED_AGENT_PRIVATE_KEY_PATH  : ~/.ssh/cloudify-agent-kp-0203.pem ...
CFY_DATA_CENTRED_MANAGER_PUBLIC_KEY_NAME : cloudify-manager-public-kp-0203 ...
CFY_DATA_CENTRED_AGENT_PUBLIC_KEY_NAME   : cloudify-agent-public-kp-0203 ...
Existing Manager IP address              : 185.43.218.157
Use existing Manager                     : true
Freeze the manager on failure            : false
manager_blueprint_file                   : /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-manager-blueprints/openstack-manager-blueprint.yaml
manager_blueprint_inputs_file            : /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-manager-blueprints/openstack-manager-blueprint-inputs.yaml
=============================================================
pre_bootstrap: execution id : 1457530162127_803100
=============================================================
run_bootstrap: execution id : 1457530162127_803100
/home/tamirk/dt_executions/1457530162127_803100 /home/tamirk/cloudify-cosmo/cloudify-deployment-tool
Cloudify CLI 3.3.1
Cloudify Manager 3.3.1 [ip=185.43.218.157]
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
Traceback (most recent call last):
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/bin/cfy", line 9, in <module>
    load_entry_point('cloudify==3.3.1', 'console_scripts', 'cfy')()
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-cli/cloudify_cli/cli.py", line 34, in main
    _configure_loggers()
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-cli/cloudify_cli/cli.py", line 188, in _configure_loggers
    logger.configure_loggers()
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-cli/cloudify_cli/logger.py", line 50, in configure_loggers
    if utils.is_initialized():
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-cli/cloudify_cli/utils.py", line 166, in is_initialized
    return get_init_path() is not None
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-cli/cloudify_cli/utils.py", line 170, in get_init_path
    current_lookup_dir = get_cwd()
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-cli/cloudify_cli/utils.py", line 260, in get_cwd
    return os.getcwd()
OSError: [Errno 2] No such file or directory
Using an existing Cloudify manager
No Need to bootstrap, running cfy use -t 185.43.218.157
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
Traceback (most recent call last):
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/bin/cfy", line 9, in <module>
    load_entry_point('cloudify==3.3.1', 'console_scripts', 'cfy')()
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-cli/cloudify_cli/cli.py", line 34, in main
    _configure_loggers()
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-cli/cloudify_cli/cli.py", line 188, in _configure_loggers
    logger.configure_loggers()
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-cli/cloudify_cli/logger.py", line 50, in configure_loggers
    if utils.is_initialized():
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-cli/cloudify_cli/utils.py", line 166, in is_initialized
    return get_init_path() is not None
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-cli/cloudify_cli/utils.py", line 170, in get_init_path
    current_lookup_dir = get_cwd()
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-cli/cloudify_cli/utils.py", line 260, in get_cwd
    return os.getcwd()
OSError: [Errno 2] No such file or directory
=============================================================
pre_blueprint_upload: execution id : 1457530162127_803100
=============================================================
blueprints_upload: execution id : 1457530162127_803100
fatal: could not create work tree dir 'cloudify-deployment-tool-apps'.: No such file or directory
Failed in git clone https://github.com/tamirko/cloudify-deployment-tool-apps.git ... - Aborting
